### ISSUE TITLE
Installation guide needed

### ISSUE THREAD

**Issue by transcendent** [henriquez/chatter-api-sample-public#5]
Some brief instructions on installation would be useful. I'm working my way through getting this running locally, and I believe that it requires SSL on the development server plus a few other things. So a consolidated set of instructions would be helpful.

**Comment by henriquez** [comment]
SSL installation varies depending on where you're installing it and there are many choices.  For SSL, here's one way if you're using Apache on a *nix machine:

https://docs.google.com/a/henriquez.net/document/d/1m0FuyRsZamQge8N0H09-HmO-6h9v9YrDhbyK1UhAm-k/edit

For deployment on Heroku, their default SSL works out of the box.  

Otherwise its a pretty standard ruby/rails/coffeescript/node project, see those projects for their respective installation instructions.

**Comment by transcendent** [comment]
Thanks henriquez. That was helpful. For reference to anyone looking for info on how to run this locally:
- start the Rails development server with thin start --ssl rather than rails s. I didn't bother to change the SSL config and lived with the cert errors.
- you need to recreate the database.yml file
- the secret_token.rb config is expecting an environment variable. I replaced it with a string.
- the omniauth.rb needs to be setup appropriately for the oauth settings in your SFDC org.
